steps:
- name: 'alpine'
  env:
    - "SERVICE=${_SERVICE}"
    - "IMAGE_INGRESS=${_IMAGE_INGRESS}"
    - "IMAGE_BACKEND=${_IMAGE_BACKEND}"
    - "IMAGE_VALIDATOR=${_IMAGE_VALIDATOR}"
    - "PORT_INGRESS=${_PORT_INGRESS}"
    - "PORT_BACKEND=${_PORT_BACKEND}"
    - "PORT_VALIDATOR=${_PORT_VALIDATOR}"
  script: |
    sed -i s@%SERVICE%@${SERVICE}@g run-service.yaml
    sed -i s@%IMAGE_INGRESS%@${IMAGE_INGRESS}@g run-service.yaml
    sed -i s@%IMAGE_BACKEND%@${IMAGE_BACKEND}@g run-service.yaml
    sed -i s@%IMAGE_VALIDATOR%@${IMAGE_VALIDATOR}@g run-service.yaml
    sed -i s@%PORT_INGRESS%@${PORT_INGRESS}@g run-service.yaml
    sed -i s@%PORT_BACKEND%@${PORT_BACKEND}@g run-service.yaml
    sed -i s@%PORT_VALIDATOR%@${PORT_VALIDATOR}@g run-service.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'services', 'replace', 'run-service.yaml',
    '--region', '${LOCATION}',
  ]

substitutions:
    _SERVICE: ob-app-sidecar
    _REPO: ob-app-sidecar-repo
    _REGISTRY: ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}
    _PORT_INGRESS: '8080'
    _PORT_BACKEND: '8082'
    _PORT_VALIDATOR: '8081'
    _NAME_INGRESS: ob-app-sidecar-develop-ingress
    _NAME_BACKEND: ob-app-sidecar-develop-backend
    _NAME_VALIDATOR: ob-app-sidecar-develop-validator
    _IMAGE_INGRESS: ${_REGISTRY}/${_NAME_INGRESS}
    _IMAGE_BACKEND: ${_REGISTRY}/${_NAME_BACKEND}
    _IMAGE_VALIDATOR: ${_REGISTRY}/${_NAME_VALIDATOR}

images:
  - ${_IMAGE_INGRESS}
  - ${_IMAGE_BACKEND}
  - ${_IMAGE_VALIDATOR}

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
