steps:
- name: 'gcr.io/cloud-builders/docker'
  id: BUILD_INGRESS
  waitFor: ['-']
  args: [
    'build', '-t', '${_IMAGE_INGRESS}',
    '-f', './Dockerfile.ingress',
    '--network=cloudbuild',
    '--platform', 'linux/amd64',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: BUILD_BACKEND
  waitFor: ['-']
  args: [
    'build', '-t', '${_IMAGE_BACKEND}',
    '-f', './Dockerfile.backend',
    '--network=cloudbuild',
    '--platform', 'linux/amd64',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: BUILD_VALIDATOR
  waitFor: ['-']
  args: [
    'build', '-t', '${_IMAGE_VALIDATOR}',
    '-f', './Dockerfile.validator',
    '--network=cloudbuild',
    '--platform', 'linux/amd64',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: PUSH_INGRESS
  waitFor: BUILD_INGRESS
  args: [
    'push', '${_IMAGE_INGRESS}'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: PUSH_BACKEND
  waitFor: BUILD_BACKEND
  args: [
    'push', '${_IMAGE_BACKEND}'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: PUSH_VALIDATOR
  waitFor: BUILD_VALIDATOR
  args: [
    'push', '${_IMAGE_VALIDATOR}'
  ]

substitutions:
    _REPO: ob-app-sidecar-repo
    _REGISTRY: ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}
    _IMAGE_INGRESS: ${_REGISTRY}/ob-app-sidecar-develop-ingress
    _IMAGE_BACKEND: ${_REGISTRY}/ob-app-sidecar-develop-backend
    _IMAGE_VALIDATOR: ${_REGISTRY}/ob-app-sidecar-develop-validator

images:
  - ${_IMAGE_INGRESS}
  - ${_IMAGE_BACKEND}
  - ${_IMAGE_VALIDATOR}

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
