services:
  ingress:
    build:
      dockerfile: ./Dockerfile.ingress-local
    ports:
      - "8080:8080"
    depends_on:
      - backend
    env_file: ".env"

  backend:
    build:
      dockerfile: ./Dockerfile.backend
    ports:
      - "8082:8082"
