apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: %SERVICE%
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: "%IMAGE_INGRESS%"
          name: ingress
          ports:
            - containerPort: '%PORT_INGRESS%'
